### ISSUE TITLE
Can't create a user with Confluence v8.1.1

### ISSUE THREAD

**Issue by molec6868** [chauth/confluence_http_authenticator#63]
I'm testing the authenticator v2.7.4 with Confluence v8.1.1.

When I try to login with a new user, it's getting stuck in a loop with shibboleth authentication.  I can see from the authenticator logs that it fails to create the user:

2023-03-20 10:53:06,661 DEBUG [http-nio-8090-exec-8] [confluence.authentication.shibboleth.RemoteUserAuthenticator] createUser Error creating user foobar. Will ignore and try to get the user (maybe it was already created)
 -- url: /index.action | userName: anonymous | referer: https://my-idp.ucl.ac.uk/ | traceId: 5c058afdc390e476
java.lang.NoClassDefFoundError: bucket/user/LicensingException
        at shibauth.confluence.authentication.shibboleth.RemoteUserAuthenticator.createUser(RemoteUserAuthenticator.java:1256)
        at shibauth.confluence.authentication.shibboleth.RemoteUserAuthenticator.createUser(RemoteUserAuthenticator.java:313)
        at shibauth.confluence.authentication.shibboleth.RemoteUserAuthenticator.getUser(RemoteUserAuthenticator.java:987)

It looks like LicensingException has been removed from v8.1.1.

I took out the reference to LicensingException and rebuilt the authenticator.  It's then failing with a different error:

2023-03-20 13:17:44,434 ERROR [http-nio-8090-exec-6] [confluence.authentication.shibboleth.RemoteUserAuthenticator] doInTransaction Failed to create user 'foobar'!
 -- url: /index.action | userName: anonymous | referer: https://my-idp.ucl.ac.uk/ | traceId: 00fc35c19ba201dc
com.atlassian.confluence.core.InsufficientPrivilegeException: User [Anonymous] does not have the required privileges.
        at com.atlassian.confluence.user.DefaultUserAccessor.createUser(DefaultUserAccessor.java:389)
        at jdk.internal.reflect.GeneratedMethodAccessor632.invoke(Unknown Source)

Are there any plans to support Confluence v8?

**Comment by molec6868** [comment]
Yes, I've compiled with the SDK v8.1.1.
<confluence.version>8.1.1</confluence.version>

**Comment by molec6868** [comment]
If I explicitly change to an admin user then it works:
`    private void createUser(final UserAccessor userAccessor, final String username, final String fullName, final String emailAddress) {
        if (username != null) {
            ConfluenceUser user = userAccessor.getUserByName(config.getAdminUser());
            AuthenticatedUserThreadLocal.set(user);
           etc, etc..
`

**Comment by johnhare** [comment]
Having same issue in v8.2.1

**Comment by vladimir-mencl-eresearch** [comment]
> If I explicitly change to an admin user then it works: ` private void createUser(final UserAccessor userAccessor, final String username, final String fullName, final String emailAddress) { if (username != null) { ConfluenceUser user = userAccessor.getUserByName(config.getAdminUser()); AuthenticatedUserThreadLocal.set(user); etc, etc..`

That looks reasonable - would you like to send in a PR fixing that?

**Comment by vladimir-mencl-eresearch** [comment]
Hi @johnhare , are you setting `adminUserId` in the config file to the name of a suitable account with administrator privileges?

**Comment by johnhare** [comment]
Adding adminUserId in the config fixed my problem. Guess I should have figured that out from the previous comments "config.getAdminUser()". Thanks for the feedback!

**Comment by vladimir-mencl-eresearch** [comment]
Thanks for the confirm - glad this solved the problem for you!
